name: CI

on:
    pull_request:
        branches:
        - "*"
        
jobs:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    - run: dotnet test MediaLibTests/MediaLibTests.csproj
        
        