name: CI
#push a second commit
on:
    pull_request:
        branches:
            - "*"
        
  # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
        
env:
  DOTNET_VERSION: '6.0.101' # The .NET SDK version to use

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: run-csharp-tests
        run: |
          dotnet test MediaLibTests/MediaLibTests.csproj
      
        
        
